#!/bin/bash
#SBATCH --mail-user=chenghao@uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/net/scratch2/chenghao/annealing_sampling/slurm_output/%A_%a.%N.stdout
#SBATCH --error=/net/scratch2/chenghao/annealing_sampling/slurm_output/%A_%a.%N.stderr
#SBATCH --chdir=/net/scratch2/chenghao/annealing_sampling/slurm_output
#SBATCH --partition=general
#SBATCH --gres=gpu:h100:4
#SBATCH --mem=600gb
#SBATCH --job-name=run_verl_annealed_sampling
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=5:59:00
#SBATCH --signal=SIGUSR1@120

#train_path=./datasets/aime_83_23_train.parquet
#test_path=./datasets/aime_83_23_val.parquet
unset ROCR_VISIBLE_DEVICES
cd /net/scratch2/chenghao/annealing_sampling
source ~/miniconda3/etc/profile.d/conda.sh
conda activate ./env
train_path="/net/scratch2/chenghao/annealing_sampling/verl/recipe/annealed_sampling/data/dapo-math-17k.parquet"
test_path="/net/scratch2/chenghao/annealing_sampling/verl/recipe/annealed_sampling/data/aime-2024.parquet"
#PROJECT_NAME="demo_verl_gsm8k_qwen2.5_1.5b_instruct"
#RUN_NAME="annealed_sampling_grpo_lower_lr_explore_${start_temp}_stable_${end_temp}_decay_freq_${decay_freq}"
PROJECT_NAME="RLVR_dapo_recipe_qwen3_1.7b_base"
#model_path=Qwen/Qwen2.5-Math-7B
    #data.tokenizer='Qwen/Qwen2.5-Math-7B' \
model_path=Qwen/Qwen3-1.7B-Base

train_files="['$train_path']"
test_files="['$test_path']"
#decay_freq=${decays[$decay_idx]}
#start_temp=${start_temps[$start_temp_idx]}
#end_temp=${end_temps[$end_temp_idx]}
decay_freq=100
start_temp=1.2
end_temp=0.1
RUN_NAME="annealed_sampling_grpo_explore_${start_temp}_stable_${end_temp}_decay_freq_${decay_freq}"
    #custom_reward_function.path='/net/scratch2/chenghao/annealing_sampling/verl/recipe/annealed_sampling/verifiable_reward.py' \
    #actor_rollout_ref.rollout.top_p=0.95 \
    #actor_rollout_ref.rollout.temperature=0.7 \
    #actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    #actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.1 \
    #actor_rollout_ref.actor.optim.min_lr_ratio=0.1 \
    #actor_rollout_ref.actor.optim.warmup_style='cosine' \
    #actor_rollout_ref.actor.grad_clip=4.0 \
    #trainer.critic_warmup=0 \
    #data.val_batch_size=1024 \
max_response_length=$((1024 * 20))
max_prompt_length=$((1024 * 2))

PYTHONUNBUFFERED=1 VLLM_USE_V1=0 python3 -m verl.trainer.main_ppo \
    data.tokenizer=${model_path} \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=512 \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.truncation='left' \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.actor.strategy='fsdp' \
    actor_rollout_ref.actor.use_torch_compile=True \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_dynamic_bsz=False \
    actor_rollout_ref.actor.grad_clip=4.0 \
    actor_rollout_ref.actor.clip_ratio=0.2 \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.fsdp_config.wrap_policy.min_num_params=1000000 \
    actor_rollout_ref.ref.fsdp_config.wrap_policy.min_num_params=1000000 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.prompt_length=640 \
    actor_rollout_ref.rollout.response_length=3456 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.max_num_batched_tokens=163840 \
    actor_rollout_ref.rollout.max_num_seqs=2048 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=False \
    actor_rollout_ref.rollout.annealed_sampling.enable=True \
    actor_rollout_ref.rollout.annealed_sampling.exploration_temp=${start_temp} \
    actor_rollout_ref.rollout.annealed_sampling.stability_temp=${end_temp} \
    actor_rollout_ref.rollout.annealed_sampling.decay_freq=${decay_freq} \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.7 \
    actor_rollout_ref.rollout.val_kwargs.n=1 \
    algorithm.adv_estimator=grpo \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$RUN_NAME \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=10 \
    trainer.total_epochs=1 $@
